spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service
  datasource:
    url : jdbc:postgresql://ec2-23-23-80-20.compute-1.amazonaws.com:5432/dfhd1136i0pjsc
    username : lgoqlblnxemzzv
    password : 44aa24baf6221edbcc29bf245edfa72003514cea1f455512ecb376773cea4cdf
    driverClassName : org.postgresql.Driver
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
    org.springframework.web: ERROR
    ca.mcgill.ecse321.rideshare9: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logging/rideshare9.log
