spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service
  datasource:
    url : jdbc:postgresql://ec2-54-227-244-12.compute-1.amazonaws.com:5432/dcr140e89ana42
    username : qafeaqjghxcbjb
    password : 85817c07188d377702c79fe357b6e3b4fdc16618769d1db640bd455f2a562493
    driverClassName : org.postgresql.Driver
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
    org.springframework.web: ERROR
    ca.mcgill.ecse321.rideshare9: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logging/rideshare9.log
